
import { Category, PopularTool } from './types';
import { 
    Ruler, 
    Weight, 
    Thermometer, 
    Square, 
    DollarSign, 
    Repeat, 
    Percent, 
    Home, 
    Briefcase, 
    Wrench, 
    Users, 
    Scale, 
    CalendarDays, 
    Tag, 
    GraduationCap, 
    TrendingUp, 
    Calculator,
    Flame,
    Beaker,
    Clock,
    PiggyBank,
    AreaChart,
    Landmark,
    Handshake,
    FileText,
    ClipboardCopy,
    Banknote,
    BookCopy,
    Database,
    HandCoins,
    HeartPulse,
    PercentCircle,
    Gauge,
    Bolt,
    Compass,
    Move,
    Power,
    Waves,
    CalendarClock,
    FileDigit,
    FileCheck,
    Files,
    Target,
    CreditCard,
    Library,
    Building2,
    ReceiptText,
    Network,
    Gift,
    Building,
    LineChart,
    ArrowRightLeft,
    CalendarPlus,
    PartyPopper,
    TimerIcon,
    // FIX: Module '"lucide-react"' has no exported member 'Stopwatch'. Using 'Timer' icon as a replacement.
    Timer as StopwatchIcon,
    Globe,
    PersonStanding,
    BedDouble,
    BrainCircuit,
    ShieldAlert,
    Cake,
    // FIX: Module '"lucide-react"' has no exported member 'ClipboardHeart'. Using 'ClipboardCheck' icon as a replacement.
    ClipboardCheck,
    GlassWater,
    Wind,
    ClipboardEdit
} from 'lucide-react';

export const CALCULATOR_CATEGORIES: Category[] = [
  {
    id: 'unit-conversion',
    name: '단위 변환기',
    icon: Ruler,
    color: 'text-emerald-500',
    tools: [
      { id: 'length', name: '길이', icon: Ruler },
      { id: 'weight', name: '무게', icon: Weight },
      { id: 'volume', name: '부피', icon: Beaker },
      { id: 'area', name: '면적', icon: Square },
      { id: 'temperature', name: '온도', icon: Thermometer },
      { id: 'time', name: '시간', icon: Clock },
      { id: 'data-storage', name: '데이터', icon: Database },
      { id: 'speed', name: '속도', icon: Gauge },
      { id: 'energy', name: '에너지', icon: Bolt },
      { id: 'pressure', name: '압력', icon: Gauge },
      { id: 'angle', name: '각도', icon: Compass },
      { id: 'force', name: '힘', icon: Move },
      { id: 'power', name: '전력', icon: Power },
      { id: 'frequency', name: '주파수', icon: Waves },
    ],
  },
  {
    id: 'finance',
    name: '금융 계산기',
    icon: DollarSign,
    color: 'text-amber-500',
    tools: [
      { id: 'exchange', name: '환율', icon: Repeat },
      { id: 'interest', name: '이자', icon: Percent },
      { id: 'savings', name: '예적금', icon: PiggyBank },
      { id: 'compound-interest', name: '복리/단리', icon: Repeat },
      { id: 'loan', name: '대출', icon: Home },
      { id: 'salary', name: '연봉', icon: Briefcase },
      { id: 'retirement', name: '퇴직금', icon: Library },
      { id: 'investment', name: '투자', icon: AreaChart },
      { id: 'annuity', name: '연금', icon: CalendarClock },
      { id: 'vat', name: '부가세', icon: FileDigit },
      { id: 'year-end-tax', name: '연말정산', icon: FileCheck },
      { id: 'income-tax', name: '종합소득세', icon: Files },
      { id: 'financial-goal', name: '목돈 만들기', icon: Target },
      { id: 'installment', name: '할부/수수료', icon: CreditCard },
      { id: 'holiday-allowance', name: '주휴수당', icon: CalendarPlus },
    ],
  },
  {
    id: 'real-estate',
    name: '부동산 툴',
    icon: Landmark,
    color: 'text-violet-500',
    tools: [
      { id: 'commission', name: '중개수수료', icon: Handshake },
      { id: 'acquisition-tax', name: '취득세', icon: FileText },
      { id: 'capital-gains-tax', name: '양도소득세', icon: ClipboardCopy },
      { id: 'comprehensive-tax', name: '종합부동산세', icon: Building2 },
      { id: 'property-tax', name: '재산세', icon: ReceiptText },
      { id: 'inheritance-tax', name: '상속세', icon: Network },
      { id: 'gift-tax', name: '증여세', icon: Gift },
      { id: 'mortgage', name: '담보대출', icon: Banknote },
      { id: 'jeonse-loan', name: '전세자금대출', icon: Building },
      { id: 'rental-yield', name: '임대수익률', icon: LineChart },
      { id: 'rent-conversion', name: '전월세 전환율', icon: ArrowRightLeft },
    ],
  },
  {
    id: 'lifestyle',
    name: '생활 편의',
    icon: Wrench,
    color: 'text-cyan-500',
    tools: [
      { id: 'dutch-pay', name: '더치페이', icon: Users },
      { id: 'd-day', name: 'D-day', icon: CalendarDays },
      { id: 'discount', name: '할인율', icon: Tag },
      { id: 'tip', name: '팁', icon: HandCoins },
      { id: 'anniversary', name: '기념일', icon: PartyPopper },
      { id: 'timer', name: '타이머', icon: TimerIcon },
      { id: 'stopwatch', name: '스톱워치', icon: StopwatchIcon },
      { id: 'world-clock', name: '세계 시간', icon: Globe },
    ],
  },
  {
    id: 'health',
    name: '건강/피트니스',
    icon: HeartPulse,
    color: 'text-pink-500',
    tools: [
        { id: 'bmi', name: '표준/이상 체중', icon: Scale },
        { id: 'calorie', name: '기초/활동대사량', icon: Flame },
        { id: 'body-fat', name: '체지방률', icon: PersonStanding },
        { id: 'visceral-fat', name: '내장 지방', icon: ClipboardCheck },
        { id: 'water-intake', name: '물 섭취량', icon: GlassWater },
        { id: 'vo2-max', name: '최대산소섭취량', icon: Wind },
        { id: 'sleep-score', name: '수면 점수', icon: BedDouble },
        { id: 'stress-level', name: '스트레스 수치', icon: BrainCircuit },
        { id: 'health-risk', name: '건강 위험도', icon: ShieldAlert },
        { id: 'biological-age', name: '생체 나이', icon: Cake },
    ],
  },
  {
    id: 'education',
    name: '교육/학습',
    icon: GraduationCap,
    color: 'text-rose-500',
    tools: [
      { id: 'grade', name: '학점', icon: TrendingUp },
      { id: 'average', name: '평균', icon: Calculator },
      { id: 'gpa', name: 'GPA 변환', icon: BookCopy },
      { id: 'percentage', name: '퍼센트', icon: PercentCircle },
      { id: 'grade-converter', name: '학점 변환', icon: ArrowRightLeft },
      { id: 'grade-predictor', name: '성적 예측', icon: ClipboardEdit },
    ],
  },
];

export const POPULAR_TOOLS: PopularTool[] = [
    { id: 'exchange', name: '환율 계산기', icon: Repeat, color: 'text-amber-500' },
    { id: 'bmi', name: 'BMI 계산기', icon: Scale, color: 'text-pink-500' },
    { id: 'dutch-pay', name: '더치페이 계산기', icon: Users, color: 'text-cyan-500' },
];
